name: "postgres"

services:
  postgres:
    image: postgres:16
    container_name: postgres16
    environment:
      POSTGRES_DB: simple_bank
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      # Performance tuning parameters
#      POSTGRES_INITDB_ARGS: "--data-checksums"
#      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
#    command: >
#      postgres
#      -c shared_buffers=2GB
#      -c effective_cache_size=6GB
#      -c maintenance_work_mem=512MB
#      -c checkpoint_completion_target=0.9
#      -c wal_buffers=16MB
#      -c default_statistics_target=100
#      -c random_page_cost=1.1
#      -c effective_io_concurrency=200
#      -c work_mem=52428kB
#      -c min_wal_size=1GB
#      -c max_wal_size=4GB
#      -c max_worker_processes=8
#      -c max_parallel_workers_per_gather=4
#      -c max_parallel_workers=8
#      -c max_parallel_maintenance_workers=4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - network1

volumes:
  postgres_data:

networks:
  network1:
    name: docker_network
    external: true